update festivals fest set tags = v.tags
from (values
  ('eurosonic-noorderslag', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('jazzfestbrno', array['Jazz']::text[]),
  ('benidorm-international-song-festival', array['Pop & Mainstream']::text[]),
  ('reverze', array['Elektronisk & Dans']::text[]),
  ('aberdeen-jazz-festival', array['Jazz']::text[]),
  ('elements-of-rock', array['Rock','Metal']::text[]),
  ('bjazz', array['Jazz']::text[]),
  ('internationale-jazzwoche-burghausen', array['Jazz']::text[]),
  ('sunice-festival-st-moritz', array['Elektronisk & Dans','Techno & House']::text[]),
  ('kelham-jazz-festival', array['Jazz']::text[]),
  ('time-warp-germany', array['Elektronisk & Dans','Techno & House']::text[]),
  ('nantwich-jazz-blues-and-music-festival', array['Jazz','Blues']::text[]),
  ('dgtl-festival-amsterdam', array['Elektronisk & Dans','Techno & House']::text[]),
  ('jazz-stroud-festival', array['Jazz']::text[]),
  ('cully-jazz-festival', array['Jazz','Blues','Soul & Funk']::text[]),
  ('april-jazz', array['Jazz','Soul & Funk']::text[]),
  ('roadburn-festival', array['Rock','Metal','Punk & Hardcore','Alternativ & Indie']::text[]),
  ('festival-baleinev', array['Rock','Metal','Pop & Mainstream','Elektronisk & Dans','Techno & House','Hip-Hop & R&B','Jazz','Soul & Funk','Folk & Americana','Verden & Reggae']::text[]),
  ('jazzfest-bonn', array['Jazz','Soul & Funk']::text[]),
  ('brick-lane-jazz-festival', array['Hip-Hop & R&B','Jazz','Soul & Funk']::text[]),
  ('jazzahead', array['Jazz','Soul & Funk']::text[]),
  ('jazzkaar', array['Alternativ & Indie','Elektronisk & Dans','Jazz']::text[]),
  ('turin-jazz-festival', array['Alternativ & Indie','Elektronisk & Dans','Jazz']::text[]),
  ('vossa-jazz', array['Alternativ & Indie','Elektronisk & Dans','Jazz']::text[]),
  ('jazzfest-gronau', array['Jazz','Blues','Soul & Funk']::text[]),
  ('cheltenham-jazz-festival', array['Jazz','Blues','Soul & Funk']::text[]),
  ('city-of-derry-jazz-festival', array['Jazz','Blues','Soul & Funk']::text[]),
  ('vina-rock', array['Rock','Metal','Punk & Hardcore','Hip-Hop & R&B']::text[]),
  ('bray-jazz-festival', array['Jazz']::text[]),
  ('concerto-del-primo-maggio', array['Rock','Alternativ & Indie','Pop & Mainstream','Hip-Hop & R&B']::text[]),
  ('balelec-festival', array['Rock','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('ravenna-jazz', array['Jazz','Soul & Funk']::text[]),
  ('kelburn-jazz-weekend', array['Jazz']::text[]),
  ('trondheim-jazz-festival', array['Jazz','Soul & Funk']::text[]),
  ('jazz-a-liege', array['Jazz','Blues','Soul & Funk']::text[]),
  ('jazz-sous-les-pommiers', array['Jazz','Blues','Soul & Funk']::text[]),
  ('birmingham-jazz-festival', array['Jazz','Blues']::text[]),
  ('dag-van-het-levenslied', array['Pop & Mainstream']::text[]),
  ('horst-music-festival', array['Elektronisk & Dans','Techno & House']::text[]),
  ('kardamili-international-jazz-festival', array['Jazz']::text[]),
  ('vicenza-jazz-festival', array['Jazz']::text[]),
  ('embassa-t', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('manchester-jazz-festival', array['Jazz','Soul & Funk']::text[]),
  ('norwich-jazz-festival', array['Jazz']::text[]),
  ('awakenings-upclose', array['Elektronisk & Dans','Techno & House']::text[]),
  ('jazz-a-saint-germain-des-pres', array['Jazz']::text[]),
  ('festival-des-3-elephants', array['Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('glyndebourne-festival-opera', array['Klassisk']::text[]),
  ('leeds-jazz-festival', array['Jazz']::text[]),
  ('moers-festival', array['Alternativ & Indie','Elektronisk & Dans','Jazz']::text[]),
  ('extrema-outdoor-belgium', array['Elektronisk & Dans','Techno & House']::text[]),
  ('a-festival', array['Rock','Pop & Mainstream','Hip-Hop & R&B','Soul & Funk']::text[]),
  ('24-heures-de-l-insa-de-lyon', array['Rock','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('festival-le-bon-air', array['Elektronisk & Dans','Techno & House']::text[]),
  ('show-of-hands-festival', array['Folk & Americana']::text[]),
  ('sidmouth-international-jazz-and-blues-festival', array['Jazz','Blues']::text[]),
  ('ikarus-festival', array['Elektronisk & Dans','Techno & House']::text[]),
  ('orange-blossom-special-festival', array['Rock','Alternativ & Indie','Folk & Americana']::text[]),
  ('weilburger-schlosskonzerte', array['Klassisk']::text[]),
  ('jazz-middelheim', array['Jazz','Blues','Soul & Funk']::text[]),
  ('7th-sunday-festival', array['Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('cross-the-tracks', array['Hip-Hop & R&B','Jazz','Soul & Funk']::text[]),
  ('garsington-opera', array['Klassisk']::text[]),
  ('sea-star-festival', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('oygospel', array['Pop & Mainstream','Soul & Funk']::text[]),
  ('blue-tone-festival', array['Jazz','Blues','Soul & Funk']::text[]),
  ('immergut-festival', array['Rock','Alternativ & Indie','Pop & Mainstream']::text[]),
  ('nattjazz', array['Alternativ & Indie','Elektronisk & Dans','Jazz','Soul & Funk']::text[]),
  ('nameless-festival', array['Elektronisk & Dans','Techno & House']::text[]),
  ('petersfield-jazz-and-blues-festival', array['Jazz','Blues']::text[]),
  ('casa-del-jazz-summer-festival', array['Jazz','Blues','Soul & Funk','Verden & Reggae']::text[]),
  ('the-grange-festival', array['Klassisk']::text[]),
  ('festival-noches-del-botanico', array['Rock','Pop & Mainstream','Jazz','Soul & Funk','Verden & Reggae']::text[]),
  ('primavera-sound', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('sweden-rock-festival', array['Rock','Metal']::text[]),
  ('northside-festival', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('lichfield-jazz-weekender', array['Jazz']::text[]),
  ('we-love-green', array['Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('jazz-festival-enkhuizen', array['Jazz']::text[]),
  ('jazz-in-the-park', array['Jazz','Soul & Funk','Verden & Reggae']::text[]),
  ('ribble-valley-jazz-and-blues', array['Jazz','Blues']::text[]),
  ('zamosti', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Soul & Funk']::text[]),
  ('bigcitybeats-world-club-dome', array['Elektronisk & Dans','Techno & House']::text[]),
  ('rock-am-ring', array['Rock','Metal','Punk & Hardcore','Alternativ & Indie','Pop & Mainstream']::text[]),
  ('rock-im-park', array['Rock','Metal','Punk & Hardcore','Alternativ & Indie','Pop & Mainstream']::text[]),
  ('verknipt-festival', array['Elektronisk & Dans','Techno & House']::text[]),
  ('swietojanskie-koncerty-organowe-im-mariana-dorawy', array['Klassisk']::text[]),
  ('wycombe-jazz-festival', array['Jazz']::text[]),
  ('opernfestspiele-heidenheim', array['Klassisk']::text[]),
  ('bergenfest', array['Rock','Alternativ & Indie','Pop & Mainstream','Hip-Hop & R&B']::text[]),
  ('glasgow-international-jazz-festival', array['Jazz','Soul & Funk']::text[]),
  ('hampton-court-palace-festival', array['Rock','Pop & Mainstream','Soul & Funk']::text[]),
  ('rock-for-people', array['Rock','Metal','Punk & Hardcore','Alternativ & Indie','Pop & Mainstream']::text[]),
  ('haze-over-haarum', array['Rock','Pop & Mainstream','Hip-Hop & R&B','Verden & Reggae']::text[]),
  ('nordalsfestivalen', array['Rock','Pop & Mainstream']::text[]),
  ('piknik-i-parken', array['Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('gottwood-festival', array['Elektronisk & Dans','Techno & House']::text[]),
  ('meltdown', array['Rock','Alternativ & Indie','Elektronisk & Dans','Hip-Hop & R&B','Jazz']::text[]),
  ('festi-neuch', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('greenfield-festival', array['Rock','Metal','Punk & Hardcore','Alternativ & Indie']::text[]),
  ('kissinger-sommer', array['Klassisk']::text[]),
  ('nova-rock-festival', array['Rock','Metal','Punk & Hardcore','Alternativ & Indie']::text[]),
  ('oper-im-steinbruch-st-margarethen', array['Klassisk']::text[]),
  ('rock-under-broen', array['Rock','Pop & Mainstream']::text[]),
  ('best-kept-secret', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans']::text[]),
  ('into-the-grave', array['Metal']::text[]),
  ('mallorca-live-festival', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('amser-jazz-time-festival', array['Jazz']::text[]),
  ('download-festival', array['Rock','Metal']::text[]),
  ('django-a-liberchies', array['Jazz']::text[]),
  ('schippop', array['Rock','Alternativ & Indie','Pop & Mainstream']::text[]),
  ('immling-festival', array['Klassisk']::text[]),
  ('nummirock', array['Metal']::text[]),
  ('caribana-festival', array['Rock','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('graspop-metal-meeting', array['Rock','Metal']::text[]),
  ('hellfest', array['Rock','Metal','Punk & Hardcore']::text[]),
  ('o-son-do-camino', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('sonar-barcelona', array['Elektronisk & Dans','Techno & House','Hip-Hop & R&B']::text[]),
  ('metronome-prague', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans']::text[]),
  ('choregies-d-orange', array['Klassisk']::text[]),
  ('pinkpop-festival', array['Rock','Alternativ & Indie','Pop & Mainstream']::text[]),
  ('trnsmt', array['Rock','Alternativ & Indie','Pop & Mainstream','Hip-Hop & R&B']::text[]),
  ('lavaux-classic', array['Klassisk']::text[]),
  ('hive-festival', array['Hip-Hop & R&B']::text[]),
  ('hurricane-festival', array['Rock','Punk & Hardcore','Alternativ & Indie','Pop & Mainstream']::text[]),
  ('splash', array['Hip-Hop & R&B']::text[]),
  ('parklife-festival', array['Pop & Mainstream','Elektronisk & Dans','Techno & House','Hip-Hop & R&B']::text[]),
  ('maifeld-derby', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans']::text[]),
  ('inmusic-festival', array['Rock','Alternativ & Indie','Pop & Mainstream']::text[]),
  ('copenhell', array['Rock','Metal']::text[]),
  ('archeo-jazz', array['Jazz']::text[]),
  ('tons-of-rock', array['Rock','Metal']::text[]),
  ('full-force', array['Metal','Punk & Hardcore']::text[]),
  ('fusion-festival', array['Alternativ & Indie','Elektronisk & Dans','Techno & House','Hip-Hop & R&B','Verden & Reggae']::text[]),
  ('kloften-festival', array['Rock','Pop & Mainstream','Folk & Americana']::text[]),
  ('tinderbox-festival', array['Rock','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('provinssi', array['Rock','Metal','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans']::text[]),
  ('jazz-a-vienne', array['Jazz']::text[]),
  ('defqon-1-festival', array['Elektronisk & Dans']::text[]),
  ('jera-on-air', array['Rock','Metal','Punk & Hardcore']::text[]),
  ('palmesus', array['Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('ascona-jazz-festival', array['Jazz']::text[]),
  ('openair-st-gallen', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B','Folk & Americana','Verden & Reggae']::text[]),
  ('jazz-baltica', array['Jazz']::text[]),
  ('comblain-jazz-festival', array['Jazz']::text[]),
  ('couleur-cafe', array['Elektronisk & Dans','Hip-Hop & R&B','Soul & Funk','Verden & Reggae']::text[]),
  ('aarhus-international-jazz-festival', array['Jazz','Soul & Funk']::text[]),
  ('tuska-open-air-metal-festival', array['Metal']::text[]),
  ('festival-de-bobital', array['Rock','Pop & Mainstream','Folk & Americana']::text[]),
  ('garorock-festival', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('solidays', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('festival-dei-due-mondi', array['Jazz','Klassisk','Verden & Reggae']::text[]),
  ('sudtirol-jazzfestival-alto-adige', array['Jazz']::text[]),
  ('n2-festival', array['Rock','Alternativ & Indie','Pop & Mainstream','Folk & Americana']::text[]),
  ('newcastle-jazz-festival', array['Jazz']::text[]),
  ('upton-jazz-festival', array['Jazz']::text[]),
  ('bad-hersfelder-festspiele', array['Pop & Mainstream','Klassisk']::text[]),
  ('werchter-boutique', array['Rock','Pop & Mainstream']::text[]),
  ('roskilde-festival', array['Rock','Metal','Punk & Hardcore','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B','Jazz','Verden & Reggae']::text[]),
  ('summer-jazz-festival-krakow', array['Jazz']::text[]),
  ('british-summer-time-hyde-park', array['Rock','Pop & Mainstream','Hip-Hop & R&B','Soul & Funk']::text[]),
  ('vilde-vulkaner-festival', array['Pop & Mainstream']::text[]),
  ('festival-de-la-cite', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Jazz','Verden & Reggae']::text[]),
  ('istanbul-jazz-festival', array['Jazz','Blues','Soul & Funk','Verden & Reggae']::text[]),
  ('festival-beauregard', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans']::text[]),
  ('festival-jazz-des-cinq-continents', array['Jazz']::text[]),
  ('festival-de-poupet', array['Rock','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('folk-music-festival-of-siglufjordur', array['Folk & Americana']::text[]),
  ('kongsberg-jazzfestival', array['Jazz','Soul & Funk']::text[]),
  ('seaside-music-og-mission-festival', array['Pop & Mainstream']::text[]),
  ('jewish-culture-festival-in-krakow', array['Jazz','Klassisk','Folk & Americana','Verden & Reggae']::text[]),
  ('open-er-festival', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('jazzx', array['Jazz']::text[]),
  ('jazz-festival-ljubljana', array['Jazz']::text[]),
  ('resurrection-fest', array['Rock','Metal','Punk & Hardcore']::text[]),
  ('lytham-festival', array['Rock','Pop & Mainstream','Soul & Funk']::text[]),
  ('obscene-extreme', array['Metal','Punk & Hardcore']::text[]),
  ('rockharz', array['Rock','Metal']::text[]),
  ('gent-jazz-festival', array['Jazz','Soul & Funk']::text[]),
  ('les-ardentes', array['Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('rock-werchter', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('aix-en-provence-festival', array['Klassisk']::text[]),
  ('charlie-jazz-festival', array['Jazz']::text[]),
  ('eurockeennes-de-belfort', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('les-eurockeennes', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('festival-celtica', array['Folk & Americana','Verden & Reggae']::text[]),
  ('stavernfestivalen', array['Rock','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('international-folklore-festival-vychodna', array['Folk & Americana','Verden & Reggae']::text[]),
  ('vida-festival', array['Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans']::text[]),
  ('festival-du-gibloux', array['Rock','Punk & Hardcore','Alternativ & Indie','Folk & Americana']::text[]),
  ('staatsforsten-open-air', array['Rock','Metal','Punk & Hardcore','Alternativ & Indie','Pop & Mainstream','Hip-Hop & R&B','Jazz','Blues','Soul & Funk','Folk & Americana','Verden & Reggae']::text[]),
  ('copenhagen-jazz-festival', array['Jazz']::text[]),
  ('hard-rock-laager', array['Metal']::text[]),
  ('ruisrock', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('savonlinna-opera-festival', array['Klassisk']::text[]),
  ('main-square-festival', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans']::text[]),
  ('kappa-futurfestival', array['Elektronisk & Dans','Techno & House']::text[]),
  ('umbria-jazz-festival', array['Jazz','Blues','Soul & Funk']::text[]),
  ('down-the-rabbit-hole', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('rock-imperium-festival', array['Rock','Metal']::text[]),
  ('cheltenham-music-festival', array['Klassisk']::text[]),
  ('love-supreme-jazz-festival', array['Jazz','Soul & Funk']::text[]),
  ('montreux-jazz-festival', array['Rock','Pop & Mainstream','Jazz','Blues','Soul & Funk']::text[]),
  ('international-music-festival-waidhofen', array['Klassisk','Folk & Americana']::text[]),
  ('parkcity-live', array['Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('godiva-festival', array['Rock','Alternativ & Indie','Pop & Mainstream','Hip-Hop & R&B']::text[]),
  ('guilfest', array['Rock','Alternativ & Indie','Pop & Mainstream','Hip-Hop & R&B']::text[]),
  ('vienna-spring-festival', array['Elektronisk & Dans','Techno & House']::text[]),
  ('llangollen-international-musical-eisteddfod', array['Klassisk','Folk & Americana','Verden & Reggae']::text[]),
  ('musilac', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans']::text[]),
  ('riddu-ri-u', array['Folk & Americana','Verden & Reggae']::text[]),
  ('traena-music-festival', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans']::text[]),
  ('beach-please', array['Hip-Hop & R&B']::text[]),
  ('pohoda', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B','Jazz','Verden & Reggae']::text[]),
  ('cruilla-barcelona', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B','Verden & Reggae']::text[]),
  ('mad-cool-festival', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans']::text[]),
  ('ortigueira-s-festival-of-celtic-world', array['Folk & Americana','Verden & Reggae']::text[]),
  ('airbeat-one', array['Elektronisk & Dans','Techno & House']::text[]),
  ('live-at-the-marquee-festival', array['Rock','Pop & Mainstream','Hip-Hop & R&B']::text[]),
  ('wereld-muziek-concours', array['Klassisk','Verden & Reggae']::text[]),
  ('slottsfjellfestivalen', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('nos-alive', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans']::text[]),
  ('garana-jazz-festival', array['Jazz']::text[]),
  ('bilbao-bbk-live', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans']::text[]),
  ('paupaterres', array['Rock','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B','Folk & Americana','Verden & Reggae']::text[]),
  ('buxton-international-music-festival', array['Jazz','Klassisk']::text[]),
  ('electric-love-festival', array['Elektronisk & Dans','Techno & House']::text[]),
  ('fm4-frequency', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('lasemo', array['Pop & Mainstream','Folk & Americana','Verden & Reggae']::text[]),
  ('rock-zottegem', array['Rock','Pop & Mainstream']::text[]),
  ('pori-jazz', array['Jazz','Blues','Soul & Funk']::text[]),
  ('chauffer-dans-la-noirceur', array['Rock','Punk & Hardcore','Alternativ & Indie','Elektronisk & Dans','Verden & Reggae']::text[]),
  ('decibulles', array['Rock','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B','Verden & Reggae']::text[]),
  ('fete-du-bruit-dans-saint-nolff', array['Rock','Pop & Mainstream']::text[]),
  ('dubrovnik-summer-festival', array['Jazz','Klassisk','Folk & Americana','Verden & Reggae']::text[]),
  ('ultra-europe', array['Elektronisk & Dans','Techno & House']::text[]),
  ('awakenings-festival', array['Elektronisk & Dans','Techno & House']::text[]),
  ('bospop', array['Rock','Blues']::text[]),
  ('north-sea-jazz', array['Hip-Hop & R&B','Jazz','Blues','Soul & Funk']::text[]),
  ('festival-internacional-de-musica-pau-casals', array['Klassisk']::text[]),
  ('portalblau', array['Rock','Pop & Mainstream','Folk & Americana','Verden & Reggae']::text[]),
  ('burton-agnes-jazz-and-blues-festival', array['Jazz','Blues']::text[]),
  ('mostly-jazz-funk-and-soul-festival', array['Jazz','Soul & Funk']::text[]),
  ('swanage-jazz-festival', array['Jazz']::text[]),
  ('tiree-music-festival', array['Rock','Pop & Mainstream','Folk & Americana']::text[]),
  ('wireless-festival', array['Hip-Hop & R&B']::text[]),
  ('rosenheim-sommerfestival', array['Rock','Pop & Mainstream']::text[]),
  ('stone-techno-festival', array['Elektronisk & Dans','Techno & House']::text[]),
  ('grafenegg-music-festival', array['Klassisk']::text[]),
  ('tw-classic', array['Rock','Pop & Mainstream']::text[]),
  ('bas-under-buen', array['Hip-Hop & R&B']::text[]),
  ('les-deferlantes-sud-de-france', array['Rock','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('pescara-jazz', array['Jazz']::text[]),
  ('verknipt-croatia', array['Elektronisk & Dans','Techno & House']::text[]),
  ('vitoria-gasteiz-jazz-festival', array['Jazz']::text[]),
  ('durham-brass-festival', array['Jazz','Soul & Funk','Klassisk','Verden & Reggae']::text[]),
  ('kaustinen-folk-music-festival', array['Folk & Americana']::text[]),
  ('molde-international-jazz-festival', array['Jazz']::text[]),
  ('les-georges', array['Rock','Punk & Hardcore','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B','Jazz']::text[]),
  ('dour-festival', array['Rock','Metal','Punk & Hardcore','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Techno & House','Hip-Hop & R&B']::text[]),
  ('cabaret-frappe', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('grimeborn', array['Klassisk']::text[]),
  ('hebridean-celtic-festival', array['Folk & Americana','Verden & Reggae']::text[]),
  ('gurtenfestival', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('colours-of-ostrava', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Jazz','Verden & Reggae']::text[]),
  ('seefestspiele-morbisch', array['Klassisk']::text[]),
  ('festival-de-la-roque-d-antheron', array['Klassisk']::text[]),
  ('festival-de-neoules', array['Rock','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B','Verden & Reggae']::text[]),
  ('vieilles-charrues-festival', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('terminal-v-croatia', array['Elektronisk & Dans','Techno & House']::text[]),
  ('zwarte-cross', array['Rock','Metal','Punk & Hardcore','Pop & Mainstream','Elektronisk & Dans']::text[]),
  ('vinjerock', array['Rock','Alternativ & Indie','Folk & Americana']::text[]),
  ('electric-castle', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Techno & House','Hip-Hop & R&B']::text[]),
  ('fib-benicassim', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('festival-internacional-de-benicassim', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('deichbrand', array['Rock','Metal','Punk & Hardcore','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('zelt-musik-festival', array['Rock','Pop & Mainstream','Jazz','Folk & Americana','Verden & Reggae']::text[]),
  ('b-my-lake', array['Elektronisk & Dans','Techno & House']::text[]),
  ('szene-openair', array['Rock','Alternativ & Indie','Pop & Mainstream','Hip-Hop & R&B']::text[]),
  ('tomorrowland', array['Elektronisk & Dans','Techno & House']::text[]),
  ('ilosaarirock', array['Rock','Metal','Punk & Hardcore','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('rockoff', array['Rock','Pop & Mainstream']::text[]),
  ('macerata-opera', array['Klassisk']::text[]),
  ('dominator-festival', array['Elektronisk & Dans']::text[]),
  ('bukta-tromso-open-air-festival', array['Rock','Metal','Punk & Hardcore','Alternativ & Indie']::text[]),
  ('jarocin-festival', array['Rock','Punk & Hardcore','Alternativ & Indie']::text[]),
  ('feslloch', array['Pop & Mainstream','Folk & Americana','Verden & Reggae']::text[]),
  ('soundit-festival', array['Elektronisk & Dans','Techno & House']::text[]),
  ('edinburgh-jazz-and-blues-festival', array['Jazz','Blues']::text[]),
  ('basel-tattoo', array['Klassisk','Folk & Americana','Verden & Reggae']::text[]),
  ('parookaville', array['Elektronisk & Dans','Techno & House']::text[]),
  ('sommerspiele-koblenz', array['Rock','Pop & Mainstream','Klassisk']::text[]),
  ('lollapalooza-paris', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('slane-concert', array['Rock','Pop & Mainstream']::text[]),
  ('fano-jazz-by-the-sea', array['Jazz']::text[]),
  ('edinburgh-festival', array['Jazz','Klassisk','Folk & Americana','Verden & Reggae']::text[]),
  ('monsters-of-rock', array['Rock','Metal']::text[]),
  ('kulturzelt', array['Rock','Pop & Mainstream','Jazz','Folk & Americana']::text[]),
  ('lollapalooza-berlin', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('international-habaneras-and-polyphony-contest-of-torrevieja', array['Klassisk','Folk & Americana','Verden & Reggae']::text[]),
  ('les-francofolies-de-spa', array['Pop & Mainstream']::text[]),
  ('cosmo-jazz', array['Jazz']::text[]),
  ('jazz-in-marciac', array['Jazz']::text[]),
  ('sligo-jazz-project', array['Jazz']::text[]),
  ('balvanyos-summer-open-university-and-student-camp', array['Rock','Pop & Mainstream','Folk & Americana']::text[]),
  ('paleo-festival', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B','Folk & Americana','Verden & Reggae']::text[]),
  ('moonjune-festival', array['Rock','Alternativ & Indie','Jazz']::text[]),
  ('canal-street', array['Pop & Mainstream','Elektronisk & Dans']::text[]),
  ('san-sebastian-jazz-festival', array['Jazz']::text[]),
  ('latitude-festival', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Jazz','Folk & Americana']::text[]),
  ('donauinselfest', array['Rock','Metal','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B','Jazz','Folk & Americana','Verden & Reggae']::text[]),
  ('sfinks-festival', array['Verden & Reggae']::text[]),
  ('viljandi-folk-music-festival', array['Folk & Americana']::text[]),
  ('delta-festival', array['Pop & Mainstream','Elektronisk & Dans','Techno & House','Hip-Hop & R&B']::text[]),
  ('alkantara-fest', array['Jazz','Folk & Americana','Verden & Reggae']::text[]),
  ('womad-charlton-park', array['Verden & Reggae']::text[]),
  ('open-air-val-lumnezia', array['Rock','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('das-fest', array['Rock','Alternativ & Indie','Pop & Mainstream','Hip-Hop & R&B','Jazz']::text[]),
  ('hills-of-rock', array['Rock','Metal']::text[]),
  ('qstock', array['Rock','Metal','Alternativ & Indie','Pop & Mainstream','Hip-Hop & R&B']::text[]),
  ('festival-de-la-paille', array['Rock','Pop & Mainstream','Elektronisk & Dans','Verden & Reggae']::text[]),
  ('les-escales', array['Pop & Mainstream','Hip-Hop & R&B','Soul & Funk','Verden & Reggae']::text[]),
  ('tolminator', array['Metal','Punk & Hardcore']::text[]),
  ('junction-2-festival', array['Elektronisk & Dans','Techno & House']::text[]),
  ('tramlines-festival', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('trowbridge-village-pump-festival', array['Folk & Americana']::text[]),
  ('bayreuth-festival', array['Klassisk']::text[]),
  ('monegros-desert-festival', array['Elektronisk & Dans','Techno & House','Hip-Hop & R&B']::text[]),
  ('ealing-jazz-festival', array['Jazz']::text[]),
  ('amphi-festival', array['Rock','Alternativ & Indie','Elektronisk & Dans']::text[]),
  ('love-family-park', array['Elektronisk & Dans','Techno & House']::text[]),
  ('rockstadt-extreme-fest', array['Rock','Metal']::text[]),
  ('bork-festival', array['Rock','Pop & Mainstream','Hip-Hop & R&B','Folk & Americana']::text[]),
  ('dekmantel-festival', array['Elektronisk & Dans','Techno & House']::text[]),
  ('beyond-the-gates', array['Metal']::text[]),
  ('ystad-sweden-jazz-festival', array['Jazz']::text[]),
  ('einhaldenfestival', array['Jazz','Folk & Americana','Verden & Reggae']::text[]),
  ('wacken-open-air', array['Metal']::text[]),
  ('grimfest', array['Rock','Metal']::text[]),
  ('castlefest', array['Rock','Folk & Americana','Verden & Reggae']::text[]),
  ('pol-and-rock-festival', array['Rock','Metal','Punk & Hardcore','Alternativ & Indie','Pop & Mainstream']::text[]),
  ('arenal-sound', array['Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('dreambeach', array['Elektronisk & Dans','Techno & House']::text[]),
  ('bestival', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('urkult', array['Folk & Americana','Verden & Reggae']::text[]),
  ('let-it-roll', array['Elektronisk & Dans']::text[]),
  ('calwer-klostersommer-in-hirsau', array['Rock','Pop & Mainstream','Jazz','Klassisk']::text[]),
  ('full-rewind-festival', array['Rock','Pop & Mainstream']::text[]),
  ('nature-one', array['Elektronisk & Dans','Techno & House']::text[]),
  ('tiroler-festspiele-erl', array['Klassisk']::text[]),
  ('sunny-hill-festival', array['Pop & Mainstream','Hip-Hop & R&B']::text[]),
  ('esperanzah', array['Rock','Pop & Mainstream','Hip-Hop & R&B','Folk & Americana','Verden & Reggae']::text[]),
  ('lokerse-feesten', array['Rock','Metal','Punk & Hardcore','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('alsace-wine-fair', array['Rock','Pop & Mainstream','Hip-Hop & R&B']::text[]),
  ('ecaussysteme', array['Rock','Pop & Mainstream','Verden & Reggae']::text[]),
  ('festival-interceltique-de-lorient', array['Folk & Americana','Verden & Reggae']::text[]),
  ('festival-du-bout-du-monde', array['Verden & Reggae']::text[]),
  ('foreztival', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('le-chien-a-plumes', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Verden & Reggae']::text[]),
  ('musicalarue', array['Rock','Pop & Mainstream','Hip-Hop & R&B','Verden & Reggae']::text[]),
  ('sylak-open-air', array['Rock','Metal']::text[]),
  ('tempo-latino', array['Soul & Funk','Verden & Reggae']::text[]),
  ('sidmouth-folk-festival', array['Folk & Americana']::text[]),
  ('festival-maritim', array['Folk & Americana','Verden & Reggae']::text[]),
  ('fahrmannsfest', array['Rock','Punk & Hardcore','Alternativ & Indie','Folk & Americana']::text[]),
  ('turku-music-festival', array['Klassisk']::text[]),
  ('cambridge-folk-festival', array['Folk & Americana']::text[]),
  ('national-eisteddfod-of-wales', array['Klassisk','Folk & Americana','Verden & Reggae']::text[]),
  ('smukfest', array['Rock','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('vagos-metal-fest', array['Metal']::text[]),
  ('medusa-festival', array['Elektronisk & Dans','Techno & House']::text[]),
  ('sonorama', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans']::text[]),
  ('boardmasters-festival', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('brutal-assault', array['Metal']::text[]),
  ('haldern-pop', array['Rock','Alternativ & Indie','Pop & Mainstream','Folk & Americana']::text[]),
  ('open-flair', array['Rock','Metal','Punk & Hardcore','Alternativ & Indie','Pop & Mainstream']::text[]),
  ('alcatraz-metal-festival', array['Metal']::text[]),
  ('ypsigrock', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans']::text[]),
  ('neopop', array['Elektronisk & Dans','Techno & House']::text[]),
  ('untold-festival', array['Pop & Mainstream','Elektronisk & Dans','Techno & House','Hip-Hop & R&B']::text[]),
  ('bloodstock-open-air', array['Metal']::text[]),
  ('brecon-jazz-festival', array['Jazz']::text[]),
  ('houghton-festival', array['Elektronisk & Dans','Techno & House']::text[]),
  ('taubertal-festival', array['Rock','Metal','Punk & Hardcore','Alternativ & Indie']::text[]),
  ('jazz-og-blues-festival-of-gouvy', array['Jazz','Blues']::text[]),
  ('suikerrock', array['Rock','Pop & Mainstream','Hip-Hop & R&B']::text[]),
  ('new-note-festival', array['Rock','Alternativ & Indie','Jazz']::text[]),
  ('hellsinki-metal-festival', array['Metal']::text[]),
  ('festival-de-bugueles', array['Rock','Pop & Mainstream','Folk & Americana','Verden & Reggae']::text[]),
  ('fete-du-bruit-dans-landerneau', array['Rock','Pop & Mainstream']::text[]),
  ('les-plages-electroniques', array['Elektronisk & Dans','Techno & House','Hip-Hop & R&B']::text[]),
  ('international-chopin-festival', array['Klassisk']::text[]),
  ('guca-trumpet-festival', array['Jazz','Folk & Americana','Verden & Reggae']::text[]),
  ('lovefest', array['Elektronisk & Dans','Techno & House']::text[]),
  ('royal-edinburgh-military-tattoo', array['Klassisk','Folk & Americana','Verden & Reggae']::text[]),
  ('southside-festival', array['Rock','Punk & Hardcore','Alternativ & Indie','Pop & Mainstream']::text[]),
  ('au-gres-du-jazz', array['Jazz']::text[]),
  ('dance-valley', array['Elektronisk & Dans','Techno & House']::text[]),
  ('radovljica-festival', array['Klassisk']::text[]),
  ('m-era-luna-festival', array['Rock','Metal','Alternativ & Indie','Elektronisk & Dans']::text[]),
  ('barrakud-croatia', array['Elektronisk & Dans','Techno & House']::text[]),
  ('oslo-jazzfestival', array['Jazz']::text[]),
  ('mish-mash-festival', array['Alternativ & Indie','Elektronisk & Dans','Jazz','Verden & Reggae']::text[]),
  ('midgardsblot', array['Rock','Metal','Folk & Americana']::text[]),
  ('rossini-opera-festival', array['Klassisk']::text[]),
  ('time-in-jazz', array['Jazz']::text[]),
  ('oyafestivalen', array['Rock','Metal','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('sziget-festival', array['Rock','Metal','Punk & Hardcore','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B','Jazz','Folk & Americana','Verden & Reggae']::text[]),
  ('la-route-du-rock', array['Rock','Alternativ & Indie','Elektronisk & Dans']::text[]),
  ('glitch-festival', array['Elektronisk & Dans','Techno & House']::text[]),
  ('boomtown', array['Rock','Punk & Hardcore','Alternativ & Indie','Elektronisk & Dans','Techno & House','Hip-Hop & R&B','Verden & Reggae']::text[]),
  ('summer-breeze-open-air', array['Metal']::text[]),
  ('summerjam', array['Verden & Reggae']::text[]),
  ('copenhagen-opera-festival', array['Klassisk']::text[]),
  ('wonderfestiwall', array['Rock','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('motocultor-festival', array['Rock','Metal','Punk & Hardcore']::text[]),
  ('zomerparkfeest', array['Rock','Pop & Mainstream','Elektronisk & Dans','Jazz','Verden & Reggae']::text[]),
  ('nisville', array['Jazz','Blues','Soul & Funk','Verden & Reggae']::text[]),
  ('east-grinstead-jazz-festival', array['Jazz']::text[]),
  ('lucerne-festival', array['Klassisk']::text[]),
  ('way-out-west', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('highfield-festival', array['Rock','Punk & Hardcore','Alternativ & Indie','Pop & Mainstream']::text[]),
  ('reload-festival', array['Rock','Metal','Punk & Hardcore']::text[]),
  ('bezemrock', array['Rock','Metal','Punk & Hardcore']::text[]),
  ('flow-festival', array['Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B','Jazz','Soul & Funk']::text[]),
  ('dynamo-metalfest', array['Metal']::text[]),
  ('nirwana-tuinfeest', array['Rock','Alternativ & Indie','Pop & Mainstream']::text[]),
  ('grape-festival', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('festival-de-jazz-de-munilla', array['Jazz']::text[]),
  ('love-parade', array['Elektronisk & Dans','Techno & House']::text[]),
  ('ms-dockville', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('inntone-jazzfestival', array['Jazz']::text[]),
  ('les-jardins-musicaux', array['Klassisk']::text[]),
  ('rencontres-de-folklore-internationales', array['Folk & Americana','Verden & Reggae']::text[]),
  ('pukkelpop', array['Rock','Metal','Punk & Hardcore','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Techno & House','Hip-Hop & R&B']::text[]),
  ('le-cabaret-vert', array['Rock','Metal','Punk & Hardcore','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('green-man-festival', array['Rock','Alternativ & Indie','Folk & Americana']::text[]),
  ('we-out-here-festival', array['Elektronisk & Dans','Hip-Hop & R&B','Jazz','Soul & Funk']::text[]),
  ('glatt-og-verkehrt', array['Folk & Americana','Verden & Reggae']::text[]),
  ('jazzfestival-saalfelden', array['Jazz']::text[]),
  ('festival-du-roi-arthur', array['Rock','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B','Verden & Reggae']::text[]),
  ('huntenpop', array['Rock','Alternativ & Indie','Pop & Mainstream']::text[]),
  ('lowlands', array['Rock','Metal','Punk & Hardcore','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Techno & House','Hip-Hop & R&B']::text[]),
  ('mystic-garden-festival', array['Elektronisk & Dans','Techno & House']::text[]),
  ('pstereo-festival', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('all-points-east', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('hip-hop-kemp', array['Hip-Hop & R&B']::text[]),
  ('zurich-openair', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('chania-chamber-music-festival', array['Klassisk']::text[]),
  ('george-enescu-festival', array['Klassisk']::text[]),
  ('les-rendez-vous-de-l-erdre', array['Jazz','Blues']::text[]),
  ('sopot-international-song-festival', array['Pop & Mainstream']::text[]),
  ('tonder-festival', array['Folk & Americana']::text[]),
  ('rock-en-seine', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans']::text[]),
  ('karrusel', array['Elektronisk & Dans','Techno & House']::text[]),
  ('sun-and-thunder-festival', array['Rock','Metal']::text[]),
  ('aberjazz', array['Jazz']::text[]),
  ('creamfields', array['Elektronisk & Dans','Techno & House']::text[]),
  ('greenbelt-festival', array['Rock','Alternativ & Indie','Pop & Mainstream','Folk & Americana','Verden & Reggae']::text[]),
  ('reading-and-leeds-festivals', array['Rock','Metal','Punk & Hardcore','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('rye-international-jazz-and-blues-festival', array['Jazz','Blues']::text[]),
  ('mysteryland', array['Elektronisk & Dans','Techno & House']::text[]),
  ('festival-de-la-luz', array['Rock','Pop & Mainstream','Folk & Americana']::text[]),
  ('the-big-feastival', array['Rock','Pop & Mainstream','Soul & Funk']::text[]),
  ('summerdays-festival', array['Rock','Pop & Mainstream']::text[]),
  ('nibirii-festival', array['Elektronisk & Dans','Techno & House','Hip-Hop & R&B']::text[]),
  ('l-afrique-en-couleurs', array['Verden & Reggae']::text[]),
  ('bude-jazz-festival', array['Jazz']::text[]),
  ('harvest-time-blues', array['Blues']::text[]),
  ('otium-festival-of-music-and-literature', array['Alternativ & Indie','Pop & Mainstream','Jazz']::text[]),
  ('punkt-festival', array['Alternativ & Indie','Elektronisk & Dans','Jazz']::text[]),
  ('swansea-international-jazz-festival', array['Jazz']::text[]),
  ('chant-du-gros', array['Rock','Pop & Mainstream','Elektronisk & Dans']::text[]),
  ('draaimolen-festival', array['Elektronisk & Dans','Techno & House']::text[]),
  ('bunkfest', array['Rock','Pop & Mainstream','Folk & Americana']::text[]),
  ('soul-town-festival', array['Soul & Funk']::text[]),
  ('leffingeleuren', array['Rock','Alternativ & Indie','Elektronisk & Dans']::text[]),
  ('ambronay-festival', array['Klassisk']::text[]),
  ('besancon-international-music-festival', array['Klassisk']::text[]),
  ('appelpop', array['Rock','Pop & Mainstream']::text[]),
  ('islay-jazz-festival', array['Jazz']::text[]),
  ('isle-of-wight-jazz-weekend', array['Jazz']::text[]),
  ('reeperbahn-festival', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('new-ross-piano-festival', array['Klassisk']::text[]),
  ('bratislava-music-festival', array['Klassisk']::text[]),
  ('newcastle-festival-of-jazz-and-improvised-music', array['Jazz']::text[]),
  ('new-colours-jazz-festival', array['Jazz']::text[]),
  ('scarborough-jazz-festival', array['Jazz']::text[]),
  ('callander-jazz-and-blues-festival', array['Jazz','Blues']::text[]),
  ('like-a-jazz-machine', array['Jazz']::text[]),
  ('henryk-wieniawski-international-violin-competition', array['Klassisk']::text[]),
  ('wexford-festival-opera', array['Klassisk']::text[]),
  ('skopje-jazz-festival', array['Jazz']::text[]),
  ('jazz-and-the-city-salzburg', array['Jazz']::text[]),
  ('leipziger-jazztage', array['Jazz']::text[]),
  ('belgrade-jazz-festival', array['Jazz']::text[]),
  ('shrewsbury-django-festival', array['Jazz']::text[]),
  ('tampere-jazz-happening', array['Jazz']::text[]),
  ('pancevo-jazz-festival', array['Jazz']::text[]),
  ('torbay-jazz', array['Jazz']::text[]),
  ('guimaraes-jazz', array['Jazz']::text[]),
  ('dundee-jazz-festival', array['Jazz']::text[]),
  ('cambridge-jazz-festival', array['Jazz']::text[]),
  ('efg-london-jazz-festival', array['Jazz']::text[]),
  ('yaouank-festival', array['Folk & Americana']::text[]),
  ('umbria-jazz-winter', array['Jazz']::text[]),
  ('festivali-i-kenges', array['Pop & Mainstream']::text[]),
  ('autumn-rock-festival', array['Rock']::text[]),
  ('boerenrock', array['Rock','Pop & Mainstream']::text[]),
  ('jazz-bilzen', array['Rock','Pop & Mainstream','Jazz','Blues','Soul & Funk']::text[]),
  ('oilsjt-omploft-fest', array['Metal','Punk & Hardcore']::text[]),
  ('midtfyns-festival', array['Rock','Pop & Mainstream']::text[]),
  ('nykobing-falster-festuge', array['Rock','Pop & Mainstream','Jazz','Folk & Americana']::text[]),
  ('rock-in-frederikshavn', array['Rock']::text[]),
  ('puntala-rock', array['Rock','Punk & Hardcore']::text[]),
  ('choralies', array['Klassisk']::text[]),
  ('crescendo-association', array['Rock','Alternativ & Indie']::text[]),
  ('django-reinhardt-jazz-festival', array['Jazz']::text[]),
  ('elektric-park-festival', array['Elektronisk & Dans','Techno & House']::text[]),
  ('europavox', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('festival-berlioz', array['Klassisk']::text[]),
  ('festival-bouche-a-oreille', array['Jazz','Folk & Americana','Verden & Reggae']::text[]),
  ('festival-kann-al-loar', array['Folk & Americana','Verden & Reggae']::text[]),
  ('festival-les-indisciplinees', array['Rock','Alternativ & Indie','Elektronisk & Dans']::text[]),
  ('festival-musique-action', array['Alternativ & Indie','Elektronisk & Dans','Jazz']::text[]),
  ('festival-tempo-rives', array['Rock','Pop & Mainstream','Folk & Americana','Verden & Reggae']::text[]),
  ('festival-terres-du-son', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B','Verden & Reggae']::text[]),
  ('festival-de-jazz-de-la-rochelle', array['Jazz']::text[]),
  ('festival-de-jazz-d-orange', array['Jazz']::text[]),
  ('festival-de-la-saint-loup', array['Folk & Americana','Verden & Reggae']::text[]),
  ('festival-de-musique-de-menton', array['Klassisk']::text[]),
  ('festival-des-arts-sonnes', array['Rock','Pop & Mainstream','Folk & Americana','Verden & Reggae']::text[]),
  ('festival-du-chant-de-marin', array['Folk & Americana','Verden & Reggae']::text[]),
  ('festival-estival-de-trelaze', array['Rock','Pop & Mainstream','Hip-Hop & R&B']::text[]),
  ('jazz-in-langourla', array['Jazz']::text[]),
  ('jazz-a-juan', array['Jazz']::text[]),
  ('kan-ar-bobl', array['Folk & Americana']::text[]),
  ('la-folle-journee', array['Klassisk']::text[]),
  ('la-poule-des-champs', array['Rock','Pop & Mainstream','Folk & Americana']::text[]),
  ('le-grand-unisson', array['Pop & Mainstream','Hip-Hop & R&B','Verden & Reggae']::text[]),
  ('le-jardin-du-michel', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('le-reve-de-l-aborigene', array['Folk & Americana','Verden & Reggae']::text[]),
  ('les-fanfarons', array['Jazz','Soul & Funk','Verden & Reggae']::text[]),
  ('les-nuits-d-istres', array['Rock','Pop & Mainstream','Jazz','Verden & Reggae']::text[]),
  ('les-suds', array['Verden & Reggae']::text[]),
  ('les-terrasses-du-jeudi', array['Rock','Alternativ & Indie','Pop & Mainstream','Verden & Reggae']::text[]),
  ('les-z-eclectiques', array['Alternativ & Indie','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('mayday-festival', array['Rock','Pop & Mainstream','Elektronisk & Dans']::text[]),
  ('metal-ride-fest', array['Metal']::text[]),
  ('nancy-jazz-pulsations', array['Hip-Hop & R&B','Jazz','Blues','Soul & Funk','Verden & Reggae']::text[]),
  ('nice-jazz-festival', array['Jazz','Blues','Soul & Funk','Verden & Reggae']::text[]),
  ('nuits-sonores', array['Elektronisk & Dans','Techno & House']::text[]),
  ('nuits-de-la-citadelle', array['Klassisk','Folk & Americana','Verden & Reggae']::text[]),
  ('opera-de-bauge', array['Klassisk']::text[]),
  ('pablo-casals-festival', array['Klassisk']::text[]),
  ('papillons-de-nuit', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('poulpaphone', array['Rock','Alternativ & Indie','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('printemps-de-bourges', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B','Verden & Reggae']::text[]),
  ('rio-loco', array['Verden & Reggae']::text[]),
  ('rolling-saone', array['Rock','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('set-electro-d-orleans', array['Elektronisk & Dans','Techno & House']::text[]),
  ('soirees-lyriques-de-sanxay', array['Klassisk']::text[]),
  ('v-og-b-fest', array['Rock','Pop & Mainstream','Elektronisk & Dans']::text[]),
  ('west-web-festival', array['Pop & Mainstream','Elektronisk & Dans']::text[]),
  ('crossover-festival', array['Rock','Alternativ & Indie','Elektronisk & Dans','Hip-Hop & R&B','Verden & Reggae']::text[]),
  ('alpen-flair', array['Rock','Metal','Folk & Americana']::text[]),
  ('laos-fest-festival-di-musica-in-calabria', array['Rock','Alternativ & Indie','Pop & Mainstream','Verden & Reggae']::text[]),
  ('padova-jazz-festival', array['Jazz']::text[]),
  ('steinegg-live', array['Rock','Pop & Mainstream','Jazz','Blues']::text[]),
  ('hideout-festival', array['Elektronisk & Dans','Techno & House']::text[]),
  ('mudri-brk-festival', array['Rock','Punk & Hardcore','Alternativ & Indie']::text[]),
  ('pannonian-challenge', array['Rock','Punk & Hardcore','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('kabaal-am-gemaal', array['Rock','Metal','Punk & Hardcore','Alternativ & Indie']::text[]),
  ('pop-on-top', array['Rock','Pop & Mainstream']::text[]),
  ('sunglow-festival', array['Elektronisk & Dans','Techno & House']::text[]),
  ('komeda-jazz-festival', array['Jazz']::text[]),
  ('ko-o-bluesa-festival', array['Blues']::text[]),
  ('angrajazz', array['Jazz']::text[]),
  ('jazz-em-agosto', array['Jazz']::text[]),
  ('larock-music-festival', array['Rock']::text[]),
  ('serbian-flute-festival-oj-moravo', array['Folk & Americana','Verden & Reggae']::text[]),
  ('punk-rock-holiday', array['Rock','Punk & Hardcore']::text[]),
  ('cant-al-ras', array['Folk & Americana']::text[]),
  ('musikaste', array['Klassisk','Folk & Americana']::text[]),
  ('trobada-d-acordionistes-del-pirineu', array['Folk & Americana','Verden & Reggae']::text[]),
  ('zaragoza-jazz-festival', array['Jazz']::text[]),
  ('aldeburgh-festival', array['Klassisk']::text[]),
  ('bbc-proms', array['Klassisk']::text[]),
  ('field-day', array['Alternativ & Indie','Elektronisk & Dans','Techno & House','Hip-Hop & R&B']::text[]),
  ('feile-an-phobail', array['Pop & Mainstream','Folk & Americana','Verden & Reggae']::text[]),
  ('glastonbury-festival', array['Rock','Metal','Punk & Hardcore','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Techno & House','Hip-Hop & R&B','Jazz','Blues','Soul & Funk','Folk & Americana','Verden & Reggae']::text[]),
  ('out-of-the-ordinary-festival', array['Alternativ & Indie','Elektronisk & Dans','Folk & Americana','Verden & Reggae']::text[]),
  ('stour-music-festival', array['Klassisk']::text[]),
  ('strawberry-fair', array['Rock','Punk & Hardcore','Alternativ & Indie','Pop & Mainstream','Folk & Americana','Verden & Reggae']::text[]),
  ('wood', array['Alternativ & Indie','Folk & Americana']::text[]),
  ('caprices-festival', array['Elektronisk & Dans','Techno & House']::text[]),
  ('festival-musique-et-neige', array['Klassisk']::text[]),
  ('fete-des-etudiants-valais', array['Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('les-francomanias', array['Rock','Pop & Mainstream']::text[]),
  ('svenska-dansbandsveckan', array['Pop & Mainstream']::text[]),
  ('kmochuv-kolin', array['Klassisk','Folk & Americana','Verden & Reggae']::text[]),
  ('magnetic-festival', array['Elektronisk & Dans','Techno & House']::text[]),
  ('mezinarodni-hudebni-festival-spilberk', array['Klassisk']::text[]),
  ('prague-spring-international-music-festival', array['Klassisk']::text[]),
  ('trutnov-open-air-music-festival', array['Rock','Punk & Hardcore','Alternativ & Indie','Folk & Americana','Verden & Reggae']::text[]),
  ('burg-herzberg-festival', array['Rock','Alternativ & Indie','Folk & Americana']::text[]),
  ('elbriot', array['Metal']::text[]),
  ('hopen-air', array['Rock','Metal']::text[]),
  ('internationales-strassenmusikfestival-baden-wurttemberg', array['Jazz','Folk & Americana','Verden & Reggae']::text[]),
  ('irish-folk-open-air-poyenberg', array['Folk & Americana']::text[]),
  ('isny-opernfestival', array['Klassisk']::text[]),
  ('keep-it-true', array['Metal']::text[]),
  ('kulturpur', array['Rock','Pop & Mainstream','Jazz','Klassisk','Folk & Americana','Verden & Reggae']::text[]),
  ('kulturarena', array['Rock','Alternativ & Indie','Pop & Mainstream','Jazz','Folk & Americana','Verden & Reggae']::text[]),
  ('lott-festival', array['Rock','Alternativ & Indie','Folk & Americana']::text[]),
  ('nation-of-gondwana', array['Elektronisk & Dans','Techno & House']::text[]),
  ('party-san-metal-open-air', array['Metal']::text[]),
  ('samba-festival-coburg', array['Verden & Reggae']::text[]),
  ('schlossgrabenfest', array['Rock','Alternativ & Indie','Pop & Mainstream','Elektronisk & Dans','Hip-Hop & R&B']::text[]),
  ('sea-you-festival', array['Elektronisk & Dans','Techno & House']::text[]),
  ('sonnemondsterne', array['Elektronisk & Dans','Techno & House']::text[]),
  ('stemweder-open-air', array['Rock','Punk & Hardcore','Alternativ & Indie','Verden & Reggae']::text[]),
  ('stustaculum', array['Rock','Alternativ & Indie','Pop & Mainstream','Jazz','Folk & Americana','Verden & Reggae']::text[]),
  ('theatron-festival', array['Rock','Alternativ & Indie','Pop & Mainstream','Hip-Hop & R&B']::text[]),
  ('umsonst-og-draussen', array['Rock','Alternativ & Indie','Pop & Mainstream','Hip-Hop & R&B','Folk & Americana','Verden & Reggae']::text[]),
  ('walkenrieder-kreuzgangkonzerte', array['Klassisk']::text[]),
  ('wave-gotik-treffen', array['Rock','Metal','Alternativ & Indie','Elektronisk & Dans']::text[]),
  ('weinturm-open-air', array['Rock','Alternativ & Indie','Folk & Americana']::text[]),
  ('wolfszeit-festival', array['Metal']::text[]),
  ('zappanale', array['Rock','Alternativ & Indie','Jazz']::text[]),
  ('bregenzer-festspiele', array['Klassisk']::text[]),
  ('linzer-klangwolke', array['Elektronisk & Dans','Klassisk']::text[])
) as v(slug, tags)
where fest.slug = v.slug;
