-- Fix: 'love-family-park' was a mislabeled duplicate of the already-correct
-- 'm-era-luna-festival' row (same Hildesheim venue coordinates, same gothic
-- lineup) — the real Love Family Park (Frankfurt techno festival) was never
-- in the database at all. Delete the duplicate before re-adding the real one.
delete from festivals where slug = 'love-family-park';

-- Add 28 electronic/techno festivals sourced from musicfestivalwizard.com,
-- cross-checked against each festival's own site for dates/venue, geocoded via Nominatim.

insert into festivals (slug, name, city, country, venue_name, website_url, category, latitude, longitude, source, external_id) values
  ('time-warp-germany', 'Time Warp Germany', 'Mannheim', 'Tyskland', 'Maimarkthalle', 'https://www.time-warp.de/germany/mannheim/', 'Techno & House', 49.4683637, 8.5239462, 'manual', 'time-warp-germany'),
  ('dgtl-festival-amsterdam', 'DGTL Festival Amsterdam', 'Amsterdam', 'Nederland', 'NDSM-werf', 'https://dgtl.nl/amsterdam/', 'Techno & House', 52.4003737, 4.8929539, 'manual', 'dgtl-festival-amsterdam'),
  ('horst-music-festival', 'Horst Music Festival', 'Vilvoorde', 'Belgia', 'Asiat Park', 'https://www.horstartsandmusic.com/festival', 'Elektronisk & Dans', 50.9406261, 4.4307282, 'manual', 'horst-music-festival'),
  ('awakenings-upclose', 'Awakenings Upclose', 'Spaarnwoude', 'Nederland', null, 'https://www.awakenings.com/', 'Techno & House', 52.40382, 4.695116, 'manual', 'awakenings-upclose'),
  ('extrema-outdoor-belgium', 'Extrema Outdoor Belgium', 'Houthalen-Helchteren', 'Belgia', null, 'https://www.extrema.be/', 'Elektronisk & Dans', 51.0566984, 5.3830618, 'manual', 'extrema-outdoor-belgium'),
  ('ikarus-festival', 'Ikarus Festival', 'Memmingen', 'Tyskland', 'Allgäu Airport', null, 'Techno & House', 47.9816221, 10.168735, 'manual', 'ikarus-festival'),
  ('festival-le-bon-air', 'Festival Le Bon Air', 'Marseille', 'Frankrike', 'Friche la Belle de Mai', 'https://www.le-bon-air.com/', 'Elektronisk & Dans', 43.2963986, 5.3777888, 'manual', 'festival-le-bon-air'),
  ('7th-sunday-festival', '7th Sunday Festival', 'Erp', 'Nederland', null, 'https://7thsunday.nl/', 'Elektronisk & Dans', 51.6004767, 5.6064592, 'manual', '7th-sunday-festival'),
  ('verknipt-festival', 'Verknipt Festival', 'Utrecht', 'Nederland', 'Strijkviertel', 'https://www.verknipt.org/', 'Techno & House', 52.0907006, 5.1215634, 'manual', 'verknipt-festival'),
  ('gottwood-festival', 'Gottwood Festival', 'Anglesey', 'Storbritannia', 'Carreglwyd Estate', 'https://www.gottwood.co.uk/', 'Elektronisk & Dans', 53.2782258, -4.3319194, 'manual', 'gottwood-festival'),
  ('hive-festival', 'Hive Festival', 'Gräfenhainichen', 'Tyskland', 'Ferropolis', 'https://www.hive-festival.de/', 'Techno & House', 51.7590874, 12.4487506, 'manual', 'hive-festival'),
  ('stone-techno-festival', 'Stone Techno Festival', 'Essen', 'Tyskland', 'Zeche Zollverein', 'https://www.stone-techno.com/', 'Techno & House', 51.488001, 7.0386873, 'manual', 'stone-techno-festival'),
  ('verknipt-croatia', 'Verknipt Croatia', 'Novalja', 'Kroatia', 'Zrće Beach', 'https://verkniptcroatia.org/', 'Techno & House', 44.5561174, 14.884472, 'manual', 'verknipt-croatia'),
  ('b-my-lake', 'B.my.Lake', 'Velence', 'Ungarn', 'North Beach', 'https://bmylake.hu/', 'Techno & House', 47.2353177, 18.6605263, 'manual', 'b-my-lake'),
  ('terminal-v-croatia', 'Terminal V Croatia', 'Tisno', 'Kroatia', 'The Garden Resort', 'https://terminalvcroatia.com/', 'Techno & House', 43.7987234, 15.6415407, 'manual', 'terminal-v-croatia'),
  ('soundit-festival', 'SoundIT Festival', 'El Prat de Llobregat', 'Spania', 'Parc Nou', 'https://www.webarcelona.net/barcelona-events/soundit-festival', 'Techno & House', 41.3167071, 2.087351, 'manual', 'soundit-festival'),
  ('delta-festival', 'Delta Festival', 'Marseille', 'Frankrike', 'Prado Beaches', 'https://www.delta-festival.com/', 'Elektronisk & Dans', 43.2963986, 5.3777888, 'manual', 'delta-festival'),
  ('junction-2-festival', 'Junction 2 Festival', 'London', 'Storbritannia', 'Boston Manor Park', 'https://www.junction2.london/', 'Techno & House', 51.4901569, -0.3188149, 'manual', 'junction-2-festival'),
  ('monegros-desert-festival', 'Monegros Desert Festival', 'Fraga', 'Spania', null, 'https://monegrosfestival.com/en', 'Elektronisk & Dans', 41.4762813, 0.2035917, 'manual', 'monegros-desert-festival'),
  ('love-family-park', 'Love Family Park', 'Frankfurt am Main', 'Tyskland', 'Rebstockpark', 'https://www.lovefamilypark.com/', 'Techno & House', 50.1105075, 8.6147248, 'manual', 'love-family-park'),
  ('neopop', 'Neopop', 'Viana do Castelo', 'Portugal', 'Forte de Santiago da Barra', 'https://neopopfestival.com/', 'Techno & House', 41.6935131, -8.828277, 'manual', 'neopop'),
  ('houghton-festival', 'Houghton Festival', 'King''s Lynn', 'Storbritannia', 'Houghton Hall', 'https://www.houghtonfestival.co.uk/', 'Elektronisk & Dans', 52.8161847, 0.6569012, 'manual', 'houghton-festival'),
  ('barrakud-croatia', 'Barrakud Croatia', 'Novalja', 'Kroatia', 'Zrće Beach', 'https://www.barrakud.com/', 'Elektronisk & Dans', 44.5561174, 14.884472, 'manual', 'barrakud-croatia'),
  ('glitch-festival', 'Glitch Festival', 'Haż-Żebbuġ', 'Malta', 'Gianpula Fields', 'https://www.glitchfestival.com/', 'Techno & House', 35.8725956, 14.4398593, 'manual', 'glitch-festival'),
  ('mystic-garden-festival', 'Mystic Garden Festival', 'Amsterdam', 'Nederland', null, 'https://www.mysticgardenfestival.nl/', 'Elektronisk & Dans', 52.3730796, 4.8924534, 'manual', 'mystic-garden-festival'),
  ('karrusel', 'Karrusel', 'Copenhagen', 'Danmark', 'Refshaleøen', 'https://www.karrusel.dk/', 'Techno & House', 55.7010478, 12.6316987, 'manual', 'karrusel'),
  ('nibirii-festival', 'Nibirii Festival', 'Düren', 'Tyskland', 'Dürener Badesee', 'https://www.nibirii.com/', 'Elektronisk & Dans', 50.8031684, 6.4820806, 'manual', 'nibirii-festival'),
  ('draaimolen-festival', 'Draaimolen Festival', 'Tilburg', 'Nederland', 'MOB Complex', 'https://draaimolen.nu/', 'Elektronisk & Dans', 51.5856185, 5.0660616, 'manual', 'draaimolen-festival')
on conflict (slug) do nothing;

insert into festival_editions (festival_id, year, date_from, date_to, program, source)
select fest.id, v.year, v.date_from::date, v.date_to::date, v.program::jsonb, 'manual'
from (values
  ('time-warp-germany', 2026, '2026-03-21', '2026-03-21', '[{"date": "2026-03-21", "day_label": null, "artists": [{"name": "Adam Beyer", "stage": null, "time": null}, {"name": "Amelie Lens", "stage": null, "time": null}, {"name": "BLOND:ISH", "stage": null, "time": null}, {"name": "Dennis Cruz", "stage": null, "time": null}, {"name": "Miss Monique", "stage": null, "time": null}, {"name": "Nina Kraviz", "stage": null, "time": null}, {"name": "Richie Hawtin", "stage": null, "time": null}, {"name": "Sara Landry", "stage": null, "time": null}, {"name": "Seth Troxler", "stage": null, "time": null}, {"name": "southstar", "stage": null, "time": null}, {"name": "Tale of Us", "stage": null, "time": null}, {"name": "Vintage Culture", "stage": null, "time": null}]}]'),
  ('dgtl-festival-amsterdam', 2026, '2026-04-03', '2026-04-05', '[{"date": "2026-04-03", "day_label": null, "artists": [{"name": "AME", "stage": null, "time": null}, {"name": "Armand Van Helden", "stage": null, "time": null}, {"name": "Bella", "stage": null, "time": null}, {"name": "Benwal", "stage": null, "time": null}, {"name": "CamelPhat", "stage": null, "time": null}, {"name": "Colyn", "stage": null, "time": null}, {"name": "Diffrent", "stage": null, "time": null}, {"name": "Dom Dolla", "stage": null, "time": null}, {"name": "Fs Green", "stage": null, "time": null}, {"name": "Gotu Jim", "stage": null, "time": null}, {"name": "Horsegiirl", "stage": null, "time": null}, {"name": "I Hate Models", "stage": null, "time": null}, {"name": "Interplanetary Criminal", "stage": null, "time": null}, {"name": "Jan Blomqvist", "stage": null, "time": null}, {"name": "Jayda G", "stage": null, "time": null}, {"name": "Joy Orbison", "stage": null, "time": null}, {"name": "Kyle Starkey", "stage": null, "time": null}, {"name": "Luuk van Dijk", "stage": null, "time": null}, {"name": "Novah", "stage": null, "time": null}, {"name": "Odymel", "stage": null, "time": null}, {"name": "Silva Bumpa", "stage": null, "time": null}, {"name": "Weval", "stage": null, "time": null}, {"name": "X Club.", "stage": null, "time": null}]}]'),
  ('horst-music-festival', 2026, '2026-05-14', '2026-05-16', '[{"date": "2026-05-14", "day_label": null, "artists": [{"name": "moe.", "stage": null, "time": null}, {"name": "Todd Edwards", "stage": null, "time": null}]}]'),
  ('awakenings-upclose', 2026, '2026-05-16', '2026-05-17', '[{"date": "2026-05-16", "day_label": null, "artists": [{"name": "Ben UFO", "stage": null, "time": null}, {"name": "Chris Liebing", "stage": null, "time": null}, {"name": "Ciara", "stage": null, "time": null}, {"name": "Ellen Allien", "stage": null, "time": null}, {"name": "Four Tet", "stage": null, "time": null}, {"name": "Jeans", "stage": null, "time": null}, {"name": "Joris Voorn", "stage": null, "time": null}, {"name": "Kobosil", "stage": null, "time": null}, {"name": "Main Phase", "stage": null, "time": null}, {"name": "Nina Kraviz", "stage": null, "time": null}, {"name": "Odymel", "stage": null, "time": null}, {"name": "Pegassi", "stage": null, "time": null}, {"name": "Quest", "stage": null, "time": null}, {"name": "Sam Alfred", "stage": null, "time": null}]}]'),
  ('extrema-outdoor-belgium', 2026, '2026-05-22', '2026-05-24', '[{"date": "2026-05-22", "day_label": null, "artists": [{"name": "Adam Beyer", "stage": null, "time": null}, {"name": "Alex Wann", "stage": null, "time": null}, {"name": "Carlita", "stage": null, "time": null}, {"name": "Claptone", "stage": null, "time": null}, {"name": "Emanuel Satie", "stage": null, "time": null}, {"name": "Franky Rizardo", "stage": null, "time": null}, {"name": "Holy Priest", "stage": null, "time": null}, {"name": "I Hate Models", "stage": null, "time": null}, {"name": "Interplanetary Criminal", "stage": null, "time": null}, {"name": "Kevin de Vries", "stage": null, "time": null}, {"name": "Luuk van Dijk", "stage": null, "time": null}, {"name": "Mahmut Orhan", "stage": null, "time": null}, {"name": "Marco Bailey", "stage": null, "time": null}, {"name": "Marco Carola", "stage": null, "time": null}, {"name": "Max Styler", "stage": null, "time": null}, {"name": "mischluft", "stage": null, "time": null}, {"name": "Nora En Pure", "stage": null, "time": null}, {"name": "Pegassi", "stage": null, "time": null}, {"name": "Sonny Fodera", "stage": null, "time": null}]}]'),
  ('ikarus-festival', 2026, '2026-05-22', '2026-05-25', '[{"date": "2026-05-22", "day_label": null, "artists": [{"name": "Angerfist", "stage": null, "time": null}, {"name": "Brutalismus 3000", "stage": null, "time": null}, {"name": "Captain Hook", "stage": null, "time": null}, {"name": "I Hate Models", "stage": null, "time": null}, {"name": "Klangkuenstler", "stage": null, "time": null}, {"name": "Paul Kalkbrenner", "stage": null, "time": null}, {"name": "Scooter", "stage": null, "time": null}, {"name": "Vini Vici", "stage": null, "time": null}]}]'),
  ('festival-le-bon-air', 2026, '2026-05-22', '2026-05-24', '[{"date": "2026-05-22", "day_label": null, "artists": [{"name": "Ellen Allien", "stage": null, "time": null}]}]'),
  ('7th-sunday-festival', 2026, '2026-05-24', '2026-05-24', '[{"date": "2026-05-24", "day_label": null, "artists": [{"name": "Axwell", "stage": null, "time": null}, {"name": "Oliver Heldens", "stage": null, "time": null}, {"name": "Outsiders", "stage": null, "time": null}, {"name": "Radical Redemption", "stage": null, "time": null}]}]'),
  ('verknipt-festival', 2026, '2026-06-06', '2026-06-07', '[{"date": "2026-06-06", "day_label": null, "artists": [{"name": "Ben Techy", "stage": null, "time": null}, {"name": "Byorn", "stage": null, "time": null}, {"name": "Fantasm", "stage": null, "time": null}, {"name": "Jayron", "stage": null, "time": null}, {"name": "Johannes Schuster", "stage": null, "time": null}, {"name": "Karah", "stage": null, "time": null}, {"name": "Klofama", "stage": null, "time": null}, {"name": "Kruelty", "stage": null, "time": null}, {"name": "Kuko", "stage": null, "time": null}, {"name": "Neek", "stage": null, "time": null}, {"name": "Nicolas Julian", "stage": null, "time": null}, {"name": "Restricted", "stage": null, "time": null}, {"name": "Toxic Machinery", "stage": null, "time": null}, {"name": "Vieze Asbak", "stage": null, "time": null}, {"name": "Winson", "stage": null, "time": null}]}]'),
  ('gottwood-festival', 2026, '2026-06-11', '2026-06-14', '[{"date": "2026-06-11", "day_label": null, "artists": [{"name": "Cesco", "stage": null, "time": null}, {"name": "Conducta", "stage": null, "time": null}, {"name": "Crazy P", "stage": null, "time": null}, {"name": "Ivy Lab", "stage": null, "time": null}, {"name": "MPH", "stage": null, "time": null}, {"name": "Oppidan", "stage": null, "time": null}, {"name": "The Trip", "stage": null, "time": null}, {"name": "Tini", "stage": null, "time": null}, {"name": "Willow", "stage": null, "time": null}]}]'),
  ('hive-festival', 2026, '2026-06-19', '2026-06-21', '[{"date": "2026-06-19", "day_label": null, "artists": [{"name": "Angerfist", "stage": null, "time": null}, {"name": "Captain Hook", "stage": null, "time": null}, {"name": "Dual Damage", "stage": null, "time": null}, {"name": "Ellen Allien", "stage": null, "time": null}, {"name": "Funk Tribu", "stage": null, "time": null}, {"name": "Holy Priest", "stage": null, "time": null}, {"name": "I Hate Models", "stage": null, "time": null}, {"name": "KETTAMA", "stage": null, "time": null}, {"name": "Klangkuenstler", "stage": null, "time": null}, {"name": "Lil Texas", "stage": null, "time": null}, {"name": "Mija", "stage": null, "time": null}, {"name": "mischluft", "stage": null, "time": null}, {"name": "Odymel", "stage": null, "time": null}, {"name": "Restricted", "stage": null, "time": null}, {"name": "Sara Landry", "stage": null, "time": null}, {"name": "southstar", "stage": null, "time": null}, {"name": "Sub Zero Project", "stage": null, "time": null}, {"name": "Vini Vici", "stage": null, "time": null}]}]'),
  ('stone-techno-festival', 2026, '2026-07-10', '2026-07-12', '[]'),
  ('verknipt-croatia', 2026, '2026-07-12', '2026-07-16', '[]'),
  ('b-my-lake', 2026, '2026-07-16', '2026-07-18', '[{"date": "2026-07-16", "day_label": null, "artists": [{"name": "Adam Beyer", "stage": null, "time": null}, {"name": "Amelie Lens", "stage": null, "time": null}, {"name": "Chris Liebing", "stage": null, "time": null}, {"name": "GENESI", "stage": null, "time": null}, {"name": "Paul Kalkbrenner", "stage": null, "time": null}, {"name": "southstar", "stage": null, "time": null}, {"name": "Sven Vath", "stage": null, "time": null}]}]'),
  ('terminal-v-croatia', 2026, '2026-07-16', '2026-07-20', '[{"date": "2026-07-16", "day_label": null, "artists": [{"name": "999999999", "stage": null, "time": null}, {"name": "Clouds", "stage": null, "time": null}, {"name": "Ellen Allien", "stage": null, "time": null}, {"name": "Ewan Mcvicar", "stage": null, "time": null}, {"name": "Hannah Laing", "stage": null, "time": null}, {"name": "Mija", "stage": null, "time": null}, {"name": "Odymel", "stage": null, "time": null}, {"name": "Pegassi", "stage": null, "time": null}, {"name": "Restricted", "stage": null, "time": null}]}]'),
  ('soundit-festival', 2026, '2026-07-17', '2026-07-18', '[{"date": "2026-07-17", "day_label": null, "artists": [{"name": "Helena Hauff", "stage": null, "time": null}, {"name": "Honey Dijon", "stage": null, "time": null}, {"name": "Nina Kraviz", "stage": null, "time": null}]}]'),
  ('delta-festival', 2026, '2026-07-23', '2026-07-26', '[{"date": "2026-07-23", "day_label": null, "artists": [{"name": "Acid Arab", "stage": null, "time": null}, {"name": "Adam Beyer", "stage": null, "time": null}, {"name": "Anoraak", "stage": null, "time": null}, {"name": "Bellini", "stage": null, "time": null}, {"name": "Bennett", "stage": null, "time": null}, {"name": "Benny Benassi", "stage": null, "time": null}, {"name": "Cascada", "stage": null, "time": null}, {"name": "Cassimm", "stage": null, "time": null}, {"name": "Cerrone", "stage": null, "time": null}, {"name": "Chambord", "stage": null, "time": null}, {"name": "Ciel.", "stage": null, "time": null}, {"name": "Dr Donk", "stage": null, "time": null}, {"name": "Ebony", "stage": null, "time": null}, {"name": "Feder", "stage": null, "time": null}, {"name": "Franglish", "stage": null, "time": null}, {"name": "Guy2bezbar", "stage": null, "time": null}, {"name": "Kevin de Vries", "stage": null, "time": null}, {"name": "Kungs", "stage": null, "time": null}, {"name": "L2B", "stage": null, "time": null}, {"name": "Leblanc", "stage": null, "time": null}, {"name": "Lilly Palmer", "stage": null, "time": null}, {"name": "Mandragora", "stage": null, "time": null}, {"name": "Matt Sassari", "stage": null, "time": null}, {"name": "MC Menor JP", "stage": null, "time": null}, {"name": "Medusa", "stage": null, "time": null}, {"name": "Miki", "stage": null, "time": null}, {"name": "Miss Monique", "stage": null, "time": null}, {"name": "Mosimann", "stage": null, "time": null}, {"name": "Niotech", "stage": null, "time": null}, {"name": "Notmytype", "stage": null, "time": null}, {"name": "Oden & Fatzo", "stage": null, "time": null}, {"name": "Pegassi", "stage": null, "time": null}, {"name": "Thylacine", "stage": null, "time": null}, {"name": "TK", "stage": null, "time": null}, {"name": "Trinix", "stage": null, "time": null}, {"name": "Vanco", "stage": null, "time": null}, {"name": "Yann Muller", "stage": null, "time": null}, {"name": "Yulia Niko", "stage": null, "time": null}]}]'),
  ('junction-2-festival', 2026, '2026-07-24', '2026-07-26', '[{"date": "2026-07-24", "day_label": null, "artists": [{"name": "Adam Beyer", "stage": null, "time": null}, {"name": "Funk Tribu", "stage": null, "time": null}, {"name": "I Hate Models", "stage": null, "time": null}, {"name": "Jeff Mills", "stage": null, "time": null}, {"name": "Miss Monique", "stage": null, "time": null}, {"name": "Nina Kraviz", "stage": null, "time": null}]}]'),
  ('monegros-desert-festival', 2026, '2026-07-25', '2026-07-25', '[]'),
  ('love-family-park', 2026, '2026-07-25', '2026-07-26', '[{"date": "2026-07-25", "day_label": null, "artists": [{"name": "BUNT.", "stage": null, "time": null}, {"name": "Charlotte De Witte", "stage": null, "time": null}, {"name": "Chris Liebing", "stage": null, "time": null}, {"name": "Chris Stussy", "stage": null, "time": null}, {"name": "Dennis Cruz", "stage": null, "time": null}, {"name": "DJ Gigola", "stage": null, "time": null}, {"name": "I Hate Models", "stage": null, "time": null}, {"name": "Joseph Capriati", "stage": null, "time": null}, {"name": "Kobosil", "stage": null, "time": null}, {"name": "Kuko", "stage": null, "time": null}, {"name": "MCR-T", "stage": null, "time": null}, {"name": "mischluft", "stage": null, "time": null}, {"name": "Mochakk", "stage": null, "time": null}, {"name": "Novah", "stage": null, "time": null}, {"name": "Solomun", "stage": null, "time": null}, {"name": "Sven Vath", "stage": null, "time": null}, {"name": "Yanamaste", "stage": null, "time": null}]}]'),
  ('neopop', 2026, '2026-08-06', '2026-08-08', '[{"date": "2026-08-06", "day_label": null, "artists": [{"name": "Chris Liebing", "stage": null, "time": null}, {"name": "DJ Gigola", "stage": null, "time": null}, {"name": "Ellen Allien", "stage": null, "time": null}, {"name": "Goldie", "stage": null, "time": null}, {"name": "Helena Hauff", "stage": null, "time": null}, {"name": "Jeff Mills", "stage": null, "time": null}, {"name": "Josh Wink", "stage": null, "time": null}, {"name": "Quest", "stage": null, "time": null}]}]'),
  ('houghton-festival', 2026, '2026-08-06', '2026-08-09', '[{"date": "2026-08-06", "day_label": null, "artists": [{"name": "Ben UFO", "stage": null, "time": null}, {"name": "Calibre", "stage": null, "time": null}, {"name": "Djrum", "stage": null, "time": null}, {"name": "Gideon", "stage": null, "time": null}, {"name": "Helena Hauff", "stage": null, "time": null}, {"name": "Kem", "stage": null, "time": null}, {"name": "Midland", "stage": null, "time": null}, {"name": "Optimo", "stage": null, "time": null}, {"name": "Scientist", "stage": null, "time": null}, {"name": "Shanti Celeste", "stage": null, "time": null}, {"name": "Willow", "stage": null, "time": null}]}]'),
  ('barrakud-croatia', 2026, '2026-08-09', '2026-08-13', '[{"date": "2026-08-09", "day_label": null, "artists": [{"name": "Deborah de Luca", "stage": null, "time": null}, {"name": "Goodboys", "stage": null, "time": null}]}]'),
  ('glitch-festival', 2026, '2026-08-12', '2026-08-15', '[{"date": "2026-08-12", "day_label": null, "artists": [{"name": "Amelie Lens", "stage": null, "time": null}, {"name": "Chris Stussy", "stage": null, "time": null}, {"name": "Funk Tribu", "stage": null, "time": null}, {"name": "mischluft", "stage": null, "time": null}, {"name": "Odymel", "stage": null, "time": null}, {"name": "Pegassi", "stage": null, "time": null}, {"name": "Quest", "stage": null, "time": null}, {"name": "Skin On Skin", "stage": null, "time": null}, {"name": "southstar", "stage": null, "time": null}]}]'),
  ('mystic-garden-festival', 2026, '2026-08-21', '2026-08-23', '[{"date": "2026-08-21", "day_label": null, "artists": [{"name": "Chris Liebing", "stage": null, "time": null}, {"name": "Main Phase", "stage": null, "time": null}, {"name": "Prunk", "stage": null, "time": null}]}]'),
  ('karrusel', 2026, '2026-08-27', '2026-08-29', '[{"date": "2026-08-27", "day_label": null, "artists": [{"name": "Amelie Lens", "stage": null, "time": null}, {"name": "Ellen Allien", "stage": null, "time": null}, {"name": "Helena Hauff", "stage": null, "time": null}, {"name": "Horsegiirl", "stage": null, "time": null}, {"name": "Monolink", "stage": null, "time": null}, {"name": "NOTION", "stage": null, "time": null}]}]'),
  ('nibirii-festival', 2026, '2026-08-28', '2026-08-30', '[{"date": "2026-08-28", "day_label": null, "artists": [{"name": "1991", "stage": null, "time": null}, {"name": "Alleycvt", "stage": null, "time": null}, {"name": "Andromedik", "stage": null, "time": null}, {"name": "Bovski", "stage": null, "time": null}, {"name": "Byorn", "stage": null, "time": null}, {"name": "Culture Shock", "stage": null, "time": null}, {"name": "Dimension", "stage": null, "time": null}, {"name": "DJ Gigola", "stage": null, "time": null}, {"name": "Ely Oaks", "stage": null, "time": null}, {"name": "Hannah Laing", "stage": null, "time": null}, {"name": "I Hate Models", "stage": null, "time": null}, {"name": "Johannes Schuster", "stage": null, "time": null}, {"name": "Klangkuenstler", "stage": null, "time": null}, {"name": "Kuko", "stage": null, "time": null}, {"name": "Lens", "stage": null, "time": null}, {"name": "Level Up", "stage": null, "time": null}, {"name": "Malugi", "stage": null, "time": null}, {"name": "Marlon Hoffstadt", "stage": null, "time": null}, {"name": "Modestep", "stage": null, "time": null}, {"name": "Mozey", "stage": null, "time": null}, {"name": "Neelix", "stage": null, "time": null}, {"name": "Oguz", "stage": null, "time": null}, {"name": "Pegassi", "stage": null, "time": null}, {"name": "Subsonic", "stage": null, "time": null}, {"name": "Vini Vici", "stage": null, "time": null}, {"name": "Wilkinson", "stage": null, "time": null}, {"name": "Winson", "stage": null, "time": null}, {"name": "Zomboy", "stage": null, "time": null}]}]'),
  ('draaimolen-festival', 2026, '2026-09-04', '2026-09-05', '[{"date": "2026-09-04", "day_label": null, "artists": [{"name": "DJ G2G", "stage": null, "time": null}, {"name": "James K", "stage": null, "time": null}, {"name": "Kevin Saunderson", "stage": null, "time": null}, {"name": "Shygirl", "stage": null, "time": null}]}]')
) as v(slug, year, date_from, date_to, program)
join festivals fest on fest.slug = v.slug
on conflict (festival_id, year) do nothing;
