-- Add 13 rock/metal festivals sourced from musicfestivalwizard.com,
-- cross-checked against each festival's own site for dates/venue, geocoded via Nominatim.

insert into festivals (slug, name, city, country, venue_name, website_url, category, latitude, longitude, source, external_id) values
  ('into-the-grave', 'Into The Grave', 'Leeuwarden', 'Nederland', 'Oldehoofsterkerkhof', 'https://intothegrave.nl/', 'Metal', 53.2005936, 5.7918548, 'manual', 'into-the-grave'),
  ('jera-on-air', 'Jera on Air', 'Ysselsteyn', 'Nederland', null, 'https://www.jeraonair.nl/', 'Punk & Hardcore', 51.4899045, 5.8961579, 'manual', 'jera-on-air'),
  ('obscene-extreme', 'Obscene Extreme', 'Trutnov', 'Tsjekkia', 'Bojiště Trutnov', 'https://obsceneextreme.cz/', 'Metal', 50.5608165, 15.912897, 'manual', 'obscene-extreme'),
  ('hills-of-rock', 'Hills Of Rock', 'Plovdiv', 'Bulgaria', 'Rowing Canal', 'https://hillsofrock.com/', 'Metal', 42.1418541, 24.7499297, 'manual', 'hills-of-rock'),
  ('amphi-festival', 'Amphi Festival', 'Köln', 'Tyskland', 'Tanzbrunnen', 'https://amphi-festival.de/', 'Blandet/Flersjanger', 50.9464129, 6.9718341, 'manual', 'amphi-festival'),
  ('beyond-the-gates', 'Beyond The Gates', 'Bergen', 'Norge', 'USF Verftet', 'https://www.beyondthegates.no/', 'Metal', 60.3943055, 5.3259192, 'manual', 'beyond-the-gates'),
  ('full-rewind-festival', 'Full Rewind Festival', 'Roitzschjora', 'Tyskland', 'Flugplatz Roitzschjora', 'https://full-rewind.de/', 'Metal', 51.5913955, 12.4859942, 'manual', 'full-rewind-festival'),
  ('sylak-open-air', 'Sylak Open Air', 'Saint-Maurice-de-Gourdans', 'Frankrike', 'Stade Régis Perrin', 'https://www.sylakopenair.com/', 'Metal', 45.8207025, 5.1936266, 'manual', 'sylak-open-air'),
  ('vagos-metal-fest', 'Vagos Metal Fest', 'Vagos', 'Portugal', 'Quinta do Ega', 'https://vagosmetalfest.com/', 'Metal', 40.5538919, -8.680915, 'manual', 'vagos-metal-fest'),
  ('hellsinki-metal-festival', 'Hellsinki Metal Festival', 'Helsinki', 'Finland', 'Helsingin Jäähalli', 'https://hellsinkimetalfestival.fi/', 'Metal', 60.1666204, 24.9435408, 'manual', 'hellsinki-metal-festival'),
  ('motocultor-festival', 'Motocultor Festival', 'Carhaix-Plouguer', 'Frankrike', 'Kerampuilh', 'https://www.motocultor-festival.com/', 'Metal', 48.2764997, -3.5711477, 'manual', 'motocultor-festival'),
  ('dynamo-metalfest', 'Dynamo Metalfest', 'Eindhoven', 'Nederland', 'IJssportcentrum', 'https://www.dynamo-metalfest.nl/', 'Metal', 51.4485569, 5.4501225, 'manual', 'dynamo-metalfest'),
  ('sun-and-thunder-festival', 'Sun & Thunder Festival', 'Fuengirola', 'Spania', 'Marenostrum Fuengirola', 'https://sunandthunderfest.com/', 'Metal', 36.5388398, -4.6233974, 'manual', 'sun-and-thunder-festival')
on conflict (slug) do nothing;

insert into festival_editions (festival_id, year, date_from, date_to, program, source)
select fest.id, v.year, v.date_from::date, v.date_to::date, v.program::jsonb, 'manual'
from (values
  ('into-the-grave', 2026, '2026-06-12', '2026-06-14', '[{"date": "2026-06-12", "day_label": null, "artists": [{"name": "Anthrax", "stage": null, "time": null}, {"name": "Conan", "stage": null, "time": null}, {"name": "Lacuna Coil", "stage": null, "time": null}, {"name": "Mastodon", "stage": null, "time": null}, {"name": "Paleface Swiss", "stage": null, "time": null}, {"name": "Queensrÿche", "stage": null, "time": null}, {"name": "Rivers of Nihil", "stage": null, "time": null}, {"name": "Self Deception", "stage": null, "time": null}, {"name": "The Browning", "stage": null, "time": null}, {"name": "The Gathering", "stage": null, "time": null}]}]'),
  ('jera-on-air', 2026, '2026-06-25', '2026-06-27', '[{"date": "2026-06-25", "day_label": null, "artists": [{"name": "A Day To Remember", "stage": null, "time": null}, {"name": "Alexisonfire", "stage": null, "time": null}, {"name": "All Time Low", "stage": null, "time": null}, {"name": "Architects", "stage": null, "time": null}, {"name": "Basement", "stage": null, "time": null}, {"name": "Bury Tomorrow", "stage": null, "time": null}, {"name": "Converge", "stage": null, "time": null}, {"name": "Distant", "stage": null, "time": null}, {"name": "End It", "stage": null, "time": null}, {"name": "Fiddlehead", "stage": null, "time": null}, {"name": "Get the Shot", "stage": null, "time": null}, {"name": "Hatebreed", "stage": null, "time": null}, {"name": "Ho99o9", "stage": null, "time": null}, {"name": "Hollywood Undead", "stage": null, "time": null}, {"name": "Imminence", "stage": null, "time": null}, {"name": "Magnolia Park", "stage": null, "time": null}, {"name": "Malevolence", "stage": null, "time": null}, {"name": "Papa Roach", "stage": null, "time": null}, {"name": "Pennywise", "stage": null, "time": null}, {"name": "Periphery", "stage": null, "time": null}, {"name": "Rise Against", "stage": null, "time": null}, {"name": "Set It Off", "stage": null, "time": null}, {"name": "Soft Play", "stage": null, "time": null}, {"name": "The Ataris", "stage": null, "time": null}, {"name": "The Baboon Show", "stage": null, "time": null}, {"name": "The Menzingers", "stage": null, "time": null}, {"name": "The Offspring", "stage": null, "time": null}, {"name": "thrown", "stage": null, "time": null}, {"name": "Trivium", "stage": null, "time": null}, {"name": "TX2", "stage": null, "time": null}, {"name": "Wargasm", "stage": null, "time": null}]}]'),
  ('obscene-extreme', 2026, '2026-07-01', '2026-07-05', '[{"date": "2026-07-01", "day_label": null, "artists": [{"name": "Converge", "stage": null, "time": null}]}]'),
  ('hills-of-rock', 2026, '2026-07-24', '2026-07-26', '[{"date": "2026-07-24", "day_label": null, "artists": [{"name": "Avatar", "stage": null, "time": null}, {"name": "Black Label Society", "stage": null, "time": null}, {"name": "Deafheaven", "stage": null, "time": null}, {"name": "Electric Callboy", "stage": null, "time": null}, {"name": "Front Line Assembly", "stage": null, "time": null}, {"name": "Godsmack", "stage": null, "time": null}, {"name": "Ho99o9", "stage": null, "time": null}, {"name": "House of Protection", "stage": null, "time": null}, {"name": "Karen Dió", "stage": null, "time": null}, {"name": "Lamb of God", "stage": null, "time": null}, {"name": "Last Train", "stage": null, "time": null}, {"name": "Malevolence", "stage": null, "time": null}, {"name": "Marilyn Manson", "stage": null, "time": null}, {"name": "Nevermore", "stage": null, "time": null}, {"name": "Northlane", "stage": null, "time": null}, {"name": "Of Mice & Men", "stage": null, "time": null}, {"name": "Orbit Culture", "stage": null, "time": null}, {"name": "P.O.D.", "stage": null, "time": null}, {"name": "Paradise Lost", "stage": null, "time": null}, {"name": "Sex Pistols", "stage": null, "time": null}, {"name": "Skindred", "stage": null, "time": null}, {"name": "The Toy Dolls", "stage": null, "time": null}, {"name": "Vended", "stage": null, "time": null}]}]'),
  ('amphi-festival', 2026, '2026-07-25', '2026-07-26', '[]'),
  ('beyond-the-gates', 2026, '2026-07-29', '2026-08-01', '[{"date": "2026-07-29", "day_label": null, "artists": [{"name": "Warning", "stage": null, "time": null}]}]'),
  ('full-rewind-festival', 2026, '2026-07-30', '2026-08-01', '[{"date": "2026-07-30", "day_label": null, "artists": [{"name": "Alien Ant Farm", "stage": null, "time": null}, {"name": "Allt", "stage": null, "time": null}, {"name": "Arch Enemy", "stage": null, "time": null}, {"name": "As Everything Unfolds", "stage": null, "time": null}, {"name": "Caliban", "stage": null, "time": null}, {"name": "Cro-Mags", "stage": null, "time": null}, {"name": "Crowbar", "stage": null, "time": null}, {"name": "Cryptopsy", "stage": null, "time": null}, {"name": "Elwood Stray", "stage": null, "time": null}, {"name": "Hatebreed", "stage": null, "time": null}, {"name": "In Flames", "stage": null, "time": null}, {"name": "Kittie", "stage": null, "time": null}, {"name": "Madball", "stage": null, "time": null}, {"name": "Paleface Swiss", "stage": null, "time": null}, {"name": "Sanguisugabogg", "stage": null, "time": null}, {"name": "Slaughter to Prevail", "stage": null, "time": null}, {"name": "Stick To Your Guns", "stage": null, "time": null}, {"name": "Terror", "stage": null, "time": null}, {"name": "Unearth", "stage": null, "time": null}]}]'),
  ('sylak-open-air', 2026, '2026-07-31', '2026-08-02', '[{"date": "2026-07-31", "day_label": null, "artists": [{"name": "Black Label Society", "stage": null, "time": null}]}]'),
  ('vagos-metal-fest', 2026, '2026-08-05', '2026-08-09', '[{"date": "2026-08-05", "day_label": null, "artists": [{"name": "Combichrist", "stage": null, "time": null}, {"name": "Cro-Mags", "stage": null, "time": null}, {"name": "Cryptopsy", "stage": null, "time": null}, {"name": "Deicide", "stage": null, "time": null}, {"name": "Godsmack", "stage": null, "time": null}, {"name": "In Flames", "stage": null, "time": null}, {"name": "Korpiklaani", "stage": null, "time": null}, {"name": "Lamb of God", "stage": null, "time": null}, {"name": "Satyricon", "stage": null, "time": null}, {"name": "ThundermoTher", "stage": null, "time": null}, {"name": "Within Temptation", "stage": null, "time": null}]}]'),
  ('hellsinki-metal-festival', 2026, '2026-08-07', '2026-08-08', '[{"date": "2026-08-07", "day_label": null, "artists": [{"name": "Accept", "stage": null, "time": null}, {"name": "Black Label Society", "stage": null, "time": null}, {"name": "Blackbraid", "stage": null, "time": null}, {"name": "Bloodbath", "stage": null, "time": null}, {"name": "Carcass", "stage": null, "time": null}, {"name": "Carpenter Brut", "stage": null, "time": null}, {"name": "Eluveitie", "stage": null, "time": null}, {"name": "Ill Niño", "stage": null, "time": null}, {"name": "Omnium Gatherum", "stage": null, "time": null}, {"name": "Opeth", "stage": null, "time": null}, {"name": "Paradise Lost", "stage": null, "time": null}, {"name": "Sanguisugabogg", "stage": null, "time": null}]}]'),
  ('motocultor-festival', 2026, '2026-08-13', '2026-08-16', '[{"date": "2026-08-13", "day_label": null, "artists": [{"name": "200 Stab Wounds", "stage": null, "time": null}, {"name": "Airbourne", "stage": null, "time": null}, {"name": "Alcest", "stage": null, "time": null}, {"name": "Amenra", "stage": null, "time": null}, {"name": "Arch Enemy", "stage": null, "time": null}, {"name": "Bloodbath", "stage": null, "time": null}, {"name": "Castle Rat", "stage": null, "time": null}, {"name": "Chelsea Grin", "stage": null, "time": null}, {"name": "Coroner", "stage": null, "time": null}, {"name": "Cryptopsy", "stage": null, "time": null}, {"name": "Deafheaven", "stage": null, "time": null}, {"name": "Death Angel", "stage": null, "time": null}, {"name": "Denez Prigent", "stage": null, "time": null}, {"name": "Eihwar", "stage": null, "time": null}, {"name": "Eisbrecher", "stage": null, "time": null}, {"name": "Emperor", "stage": null, "time": null}, {"name": "Filth", "stage": null, "time": null}, {"name": "Fit For An Autopsy", "stage": null, "time": null}, {"name": "Gaerea", "stage": null, "time": null}, {"name": "Godsmack", "stage": null, "time": null}, {"name": "Ill Niño", "stage": null, "time": null}, {"name": "Judas Priest", "stage": null, "time": null}, {"name": "Kim Dracula", "stage": null, "time": null}, {"name": "Kittie", "stage": null, "time": null}, {"name": "Leprous", "stage": null, "time": null}, {"name": "Lord of the Lost", "stage": null, "time": null}, {"name": "Mass Hysteria", "stage": null, "time": null}, {"name": "Master Boot Record", "stage": null, "time": null}, {"name": "Miracle of Sound", "stage": null, "time": null}, {"name": "Municipal Waste", "stage": null, "time": null}, {"name": "Nanowar of Steel", "stage": null, "time": null}, {"name": "Nevermore", "stage": null, "time": null}, {"name": "Omnium Gatherum", "stage": null, "time": null}, {"name": "Oomph!", "stage": null, "time": null}, {"name": "Orden Ogan", "stage": null, "time": null}, {"name": "Paradise Lost", "stage": null, "time": null}, {"name": "Perturbator", "stage": null, "time": null}, {"name": "Primus", "stage": null, "time": null}, {"name": "Sanguisugabogg", "stage": null, "time": null}, {"name": "Sierra Veins", "stage": null, "time": null}, {"name": "Signs of The Swarm", "stage": null, "time": null}, {"name": "Slaughter to Prevail", "stage": null, "time": null}, {"name": "Soen", "stage": null, "time": null}, {"name": "Textures", "stage": null, "time": null}, {"name": "The Casualties", "stage": null, "time": null}, {"name": "Unearth", "stage": null, "time": null}, {"name": "Vader", "stage": null, "time": null}, {"name": "Visions of Atlantis", "stage": null, "time": null}, {"name": "Voivod", "stage": null, "time": null}, {"name": "Warning", "stage": null, "time": null}, {"name": "Within Temptation", "stage": null, "time": null}]}]'),
  ('dynamo-metalfest', 2026, '2026-08-14', '2026-08-16', '[{"date": "2026-08-14", "day_label": null, "artists": [{"name": "200 Stab Wounds", "stage": null, "time": null}, {"name": "Amorphis", "stage": null, "time": null}, {"name": "Bleed From Within", "stage": null, "time": null}, {"name": "Castle Rat", "stage": null, "time": null}, {"name": "Death Angel", "stage": null, "time": null}, {"name": "Destruction", "stage": null, "time": null}, {"name": "Filth", "stage": null, "time": null}, {"name": "Fit For An Autopsy", "stage": null, "time": null}, {"name": "Godsmack", "stage": null, "time": null}, {"name": "Helloween", "stage": null, "time": null}, {"name": "Hyro the Hero", "stage": null, "time": null}, {"name": "In Flames", "stage": null, "time": null}, {"name": "Kittie", "stage": null, "time": null}, {"name": "Lamb of God", "stage": null, "time": null}, {"name": "Lowen", "stage": null, "time": null}, {"name": "Overkill", "stage": null, "time": null}, {"name": "Primus", "stage": null, "time": null}, {"name": "Revocation", "stage": null, "time": null}, {"name": "Sanguisugabogg", "stage": null, "time": null}, {"name": "Self Deception", "stage": null, "time": null}, {"name": "Slaughter to Prevail", "stage": null, "time": null}, {"name": "Soulfly", "stage": null, "time": null}, {"name": "Tailgunner", "stage": null, "time": null}, {"name": "Testament", "stage": null, "time": null}, {"name": "Thy Art Is Murder", "stage": null, "time": null}]}]'),
  ('sun-and-thunder-festival', 2026, '2026-08-27', '2026-08-29', '[{"date": "2026-08-27", "day_label": null, "artists": [{"name": "Twisted Sister", "stage": null, "time": null}]}]')
) as v(slug, year, date_from, date_to, program)
join festivals fest on fest.slug = v.slug
on conflict (festival_id, year) do nothing;
